//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AwardManagment.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class ApplicationDetail
    {
        public System.Guid AppId { get; set; }
        public System.Guid QueId { get; set; }
        public string Answer { get; set; }
    
        public virtual Application Application { get; set; }
        public virtual Question Question { get; set; }
    }
}
